// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbpVG_S43jKPCzeV1n1kz_kqY9G8AHb4k',
    appId: '1:909524036356:web:34ac582876297e75873e51',
    messagingSenderId: '909524036356',
    projectId: 'supreme-institution',
    authDomain: 'supreme-institution.firebaseapp.com',
    storageBucket: 'supreme-institution.firebasestorage.app',
    measurementId: 'G-67PH4T3NJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw21avwK5PuTSYd7rF_vk9Uq2zvLb9Ugg',
    appId: '1:909524036356:android:d715b9f8693be0ce873e51',
    messagingSenderId: '909524036356',
    projectId: 'supreme-institution',
    storageBucket: 'supreme-institution.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo830K6Dn-Do-4X-UFoCyW_yCl3plmnFk',
    appId: '1:909524036356:ios:7afe21280da543f9873e51',
    messagingSenderId: '909524036356',
    projectId: 'supreme-institution',
    storageBucket: 'supreme-institution.firebasestorage.app',
    iosBundleId: 'com.example.supremeInstitution',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo830K6Dn-Do-4X-UFoCyW_yCl3plmnFk',
    appId: '1:909524036356:ios:7afe21280da543f9873e51',
    messagingSenderId: '909524036356',
    projectId: 'supreme-institution',
    storageBucket: 'supreme-institution.firebasestorage.app',
    iosBundleId: 'com.example.supremeInstitution',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbpVG_S43jKPCzeV1n1kz_kqY9G8AHb4k',
    appId: '1:909524036356:web:26be29f77209d843873e51',
    messagingSenderId: '909524036356',
    projectId: 'supreme-institution',
    authDomain: 'supreme-institution.firebaseapp.com',
    storageBucket: 'supreme-institution.firebasestorage.app',
    measurementId: 'G-WNMWW6B6PF',
  );
}
