import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:supreme_institution/models/college.dart';
import 'package:supreme_institution/models/employee.dart';
import '../providers/college_provider.dart';
import '../providers/employee_provider.dart';
import '../services/auth_storage_service.dart';
import '../services/notification_service.dart';

class LoginScreen extends StatefulWidget {
  const LoginScreen({super.key});

  @override
  State<LoginScreen> createState() => _LoginScreenState();
}

class _LoginScreenState extends State<LoginScreen> {
  final _formKey = GlobalKey<FormState>();
  final TextEditingController _emailController = TextEditingController();
  final TextEditingController _passwordController = TextEditingController();
  bool _obscurePassword = true;
  bool _isLoading = false;
  List<String> _allLogins = [];
  List<String> _filteredLogins = [];
  String? _selectedLogin;
  bool _isInitialLoad = true;
  bool _showSuggestions = false;

  @override
  void initState() {
    super.initState();
    _fetchAllLogins();
    _emailController.addListener(_onEmailChanged);
  }

  @override
  void dispose() {
    _emailController.removeListener(_onEmailChanged);
    _emailController.dispose();
    _passwordController.dispose();
    super.dispose();
  }

  void _onEmailChanged() {
    final input = _emailController.text.trim();
    setState(() {
      if (input.isEmpty) {
        _filteredLogins = [];
        _showSuggestions = false;
      } else {
        _filteredLogins = _allLogins
            .where((login) => login.toLowerCase().contains(input.toLowerCase()))
            .toList();
        _showSuggestions = _filteredLogins.isNotEmpty;
      }
    });
  }

  void _selectLogin(String login) {
    setState(() {
      _selectedLogin = login;
      _emailController.text = login;
      _showSuggestions = false;
      _filteredLogins = [];
    });
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    // Refresh data only on subsequent visits, not initial load
    if (!_isInitialLoad) {
      _fetchAllLogins();
    }
    _isInitialLoad = false;
  }

  Future<void> _fetchAllLogins() async {
    final collegeProvider = Provider.of<CollegeProvider>(context, listen: false);
    final employeeProvider = Provider.of<EmployeeProvider>(context, listen: false);
    await collegeProvider.fetchColleges();
    await employeeProvider.fetchEmployees();
    final logins = <String>[];
    logins.addAll(collegeProvider.colleges.map((c) => c.id));
    logins.addAll(employeeProvider.employees.map((e) => e.id));
    logins.add('supreme@supreme.com');
    setState(() {
      _allLogins = logins;
    });
  }

  void _togglePasswordVisibility() {
    setState(() {
      _obscurePassword = !_obscurePassword;
    });
  }

  void _showAboutDialog() {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
        title: Row(
          children: [
            const Icon(Icons.info_outline, color: Color(0xFF2563EB)),
            const SizedBox(width: 10),
            const Text('About QRmed'),
          ],
        ),
        content: SizedBox(
          width: double.maxFinite,
          child: SingleChildScrollView(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              mainAxisSize: MainAxisSize.min,
              children: [
                const Text(
                  'QRmed is a smart equipment management system. We onboard your institution, calculate required equipment based on seats, departments, and standards, and digitally manage every asset using QR technology.',
                  style: TextStyle(fontSize: 14, height: 1.5),
                ),
                const SizedBox(height: 16),
                const Text(
                  'Each equipment receives a QR sticker generated by the QRmed app, making tracking, maintenance, and inspections simple and transparent.',
                  style: TextStyle(fontSize: 14, height: 1.5),
                ),
                const SizedBox(height: 24),
                _buildAboutSection(
                  title: '✅ How QRmed Works',
                  items: [
                    'We analyze your college based on departments and student intake.',
                    'Required equipment is calculated and added into the system.',
                    'A unique QR code sticker is generated for every machine.',
                    'Anyone can scan the QR to instantly view equipment details.',
                    'If equipment is not working, service can be reported immediately.',
                  ],
                ),
                const SizedBox(height: 24),
                const Text(
                  '⭐ Why Choose QRmed?',
                  style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16, color: Color(0xFF2563EB)),
                ),
                const SizedBox(height: 12),
                _buildFeatureItem(
                  icon: Icons.inventory_2_outlined,
                  title: 'QR-Powered Inventory',
                  description: 'Every equipment gets a unique QR sticker.',
                ),
                _buildFeatureItem(
                  icon: Icons.qr_code_scanner,
                  title: 'Scan to View',
                  description: 'Technical specifications, manuals, serial numbers, and current working status.',
                ),
                _buildFeatureItem(
                  icon: Icons.report_problem_outlined,
                  title: 'Scan to Report',
                  description: 'Instantly mark equipment as "Not Working" and request repair quickly.',
                ),
                _buildFeatureItem(
                  icon: Icons.fact_check_outlined,
                  title: 'Inspection Tool',
                  description: 'Government-based comparison to identify missing equipment and stay inspection-ready.',
                ),
                _buildFeatureItem(
                  icon: Icons.table_view_outlined,
                  title: 'Data at Your Fingertips',
                  description: 'One-click Export to Excel for audits and official record submissions.',
                ),
                _buildFeatureItem(
                  icon: Icons.account_tree_outlined,
                  title: 'Department Mapping',
                  description: 'Track equipment department-wise with clear allocation.',
                ),
                _buildFeatureItem(
                  icon: Icons.build_circle_outlined,
                  title: 'Automatic Service',
                  description: 'Easy service reporting, maintenance tracking, and history management.',
                ),
                _buildFeatureItem(
                  icon: Icons.account_balance_wallet_outlined,
                  title: 'Investment Management',
                  description: 'Monitor equipment investment and manage assets efficiently.',
                ),
                const SizedBox(height: 24),
                Container(
                  padding: const EdgeInsets.all(12),
                  decoration: BoxDecoration(
                    color: Colors.blue.shade50,
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Row(
                    children: [
                      const Icon(Icons.phone, color: Color(0xFF2563EB), size: 20),
                      const SizedBox(width: 10),
                      const Text(
                        'Contact: +91 99491 68999',
                        style: TextStyle(fontWeight: FontWeight.bold, color: Color(0xFF1E40AF)),
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Close'),
          ),
        ],
      ),
    );
  }

  Widget _buildAboutSection({required String title, required List<String> items}) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          title,
          style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16, color: Color(0xFF2563EB)),
        ),
        const SizedBox(height: 10),
        ...items.map((item) => Padding(
              padding: const EdgeInsets.only(bottom: 8.0),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Text('🔹 ', style: TextStyle(fontSize: 14)),
                  Expanded(child: Text(item, style: const TextStyle(fontSize: 14))),
                ],
              ),
            )),
      ],
    );
  }

  Widget _buildFeatureItem({required IconData icon, required String title, required String description}) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 16.0),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Icon(icon, size: 20, color: Colors.blueGrey),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(title, style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 14)),
                const SizedBox(height: 2),
                Text(description, style: TextStyle(fontSize: 13, color: Colors.grey.shade700)),
              ],
            ),
          ),
        ],
      ),
    );
  }

  void _login() async {
    if (!_formKey.currentState!.validate()) return;
    setState(() => _isLoading = true);
    final email = _emailController.text.trim();
    final password = _passwordController.text;
    await Future.delayed(const Duration(milliseconds: 500));

    // Admin login
    if (email == 'supreme@supreme.com' && password == '1234567890') {
      setState(() => _isLoading = false);
      // Save login credentials
      await AuthStorageService.saveLoginCredentials(
        email: email,
        password: password,
        userType: 'admin',
      );
      Navigator.of(context).pushReplacementNamed('/admin');
      return;
    }

    // College login
    final collegeProvider = Provider.of<CollegeProvider>(context, listen: false);
    College? college;
    try {
      college = collegeProvider.colleges.firstWhere((c) => c.id == email && c.password == password);
    } catch (_) {
      college = null;
    }
    if (college != null) {
      setState(() => _isLoading = false);
      // Save login credentials
      await AuthStorageService.saveLoginCredentials(
        email: email,
        password: password,
        userType: 'college',
        collegeId: college.id,
      );
      Navigator.of(context).pushReplacementNamed(
        '/collegeDashboard',
        arguments: college.id,
      );
      return;
    }

    // Employee login
    final employeeProvider = Provider.of<EmployeeProvider>(context, listen: false);
    Employee? employee;
    try {
      employee = employeeProvider.employees.firstWhere((e) => e.id == email && e.password == password);
    } catch (_) {
      employee = null;
    }
    if (employee != null) {
      // Verify employee still exists in Firebase (to catch deleted employees)
      final verifyEmployee = await employeeProvider.getEmployeeById(employee.id);
      if (verifyEmployee == null) {
        setState(() => _isLoading = false);
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Invalid credentials. Employee account not found.')),
        );
        return;
      }
      setState(() => _isLoading = false);
      final collegeProvider = Provider.of<CollegeProvider>(context, listen: false);
      String collegeName = 'College'; // Default name
      try {
        final college = collegeProvider.colleges.firstWhere((c) => c.id == employee!.collegeId);
        collegeName = college.name;
      } catch (_) {
        collegeName = 'College'; // College not found, use default
        debugPrint("Could not find college for employee. Using default name.");
      }
      // Save login credentials
      await AuthStorageService.saveLoginCredentials(
        email: email,
        password: password,
        userType: 'employee',
        collegeId: employee.collegeId,
        collegeName: collegeName,
      );
      Navigator.of(context).pushReplacementNamed('/employeeDashboard',
          arguments: {'employeeId': employee.id, 'collegeName': collegeName});
      return;
    }

    setState(() => _isLoading = false);
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('Invalid credentials.')),
    );
  }

  @override
  Widget build(BuildContext context) {
    final size = MediaQuery.of(context).size;
    return Scaffold(
      body: Stack(
        children: [
          Container(
            decoration: const BoxDecoration(
              gradient: LinearGradient(
                begin: Alignment.topLeft,
                end: Alignment.bottomRight,
                colors: [Color(0xFF2563EB), Color(0xFF1E40AF)],
              ),
            ),
            child: Center(
              child: SingleChildScrollView(
                padding: const EdgeInsets.symmetric(horizontal: 24.0, vertical: 16),
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    // Logo and Header
                    Container(
                      padding: const EdgeInsets.all(20),
                      decoration: BoxDecoration(
                        color: Colors.white.withOpacity(0.1),
                        borderRadius: BorderRadius.circular(20),
                      ),
                      child: const Icon(Icons.qr_code_scanner, size: 60, color: Colors.white),
                    ),
                    const SizedBox(height: 24),
                    const Text(
                      'QRmed',
                      style: TextStyle(
                        fontSize: 32,
                        fontWeight: FontWeight.bold,
                        color: Colors.white,
                      ),
                    ),
                    const SizedBox(height: 4),
                    Container(
                      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 3),
                      decoration: BoxDecoration(
                        color: Colors.white,
                        borderRadius: BorderRadius.circular(4),
                      ),
                      child: const Text(
                        'SUPREME BIOMEDICAL',
                        textAlign: TextAlign.center,
                        maxLines: 1,
                        style: TextStyle(
                          fontSize: 12,
                          fontWeight: FontWeight.bold,
                          color: Colors.black,
                          letterSpacing: 1.0,
                        ),
                      ),
                    ),
                    const SizedBox(height: 12),
                    Text(
                      'Medical Equipment Management',
                      style: TextStyle(
                        fontSize: 14,
                        color: Colors.white.withOpacity(0.9),
                      ),
                    ),
                    const SizedBox(height: 48),
                    
                    // Login Form
                    Container(
                      padding: const EdgeInsets.all(24),
                      decoration: BoxDecoration(
                        color: Colors.white,
                        borderRadius: BorderRadius.circular(20),
                        boxShadow: [
                          BoxShadow(
                            color: Colors.black.withOpacity(0.1),
                            blurRadius: 10,
                            offset: const Offset(0, 5),
                          ),
                        ],
                      ),
                      child: Form(
                        key: _formKey,
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            TextFormField(
                              controller: _emailController,
                              decoration: InputDecoration(
                                labelText: 'Login ID',
                                hintText: 'Enter your login ID',
                                prefixIcon: const Icon(Icons.account_circle),
                                border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
                              ),
                              validator: (value) {
                                if (value == null || value.isEmpty) {
                                  return 'Please enter a login ID';
                                }
                                return null;
                              },
                            ),
                            if (_showSuggestions)
                              Container(
                                margin: const EdgeInsets.only(top: 8),
                                constraints: const BoxConstraints(maxHeight: 200),
                                decoration: BoxDecoration(
                                  color: Colors.white,
                                  border: Border.all(color: Colors.grey.shade300),
                                  borderRadius: BorderRadius.circular(12),
                                ),
                                child: ListView.builder(
                                  shrinkWrap: true,
                                  itemCount: _filteredLogins.length,
                                  itemBuilder: (context, index) {
                                    final login = _filteredLogins[index];
                                    return InkWell(
                                      onTap: () => _selectLogin(login),
                                      child: Padding(
                                        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                                        child: Text(login, style: const TextStyle(fontSize: 13)),
                                      ),
                                    );
                                  },
                                ),
                              ),
                            const SizedBox(height: 16),
                            TextFormField(
                              controller: _passwordController,
                              obscureText: _obscurePassword,
                              decoration: InputDecoration(
                                labelText: 'Password',
                                hintText: 'Enter your password',
                                prefixIcon: const Icon(Icons.lock),
                                suffixIcon: IconButton(
                                  icon: Icon(_obscurePassword ? Icons.visibility_off : Icons.visibility),
                                  onPressed: _togglePasswordVisibility,
                                ),
                                border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
                              ),
                              validator: (value) {
                                if (value == null || value.isEmpty) {
                                  return 'Please enter your password';
                                }
                                if (value.length < 6) {
                                  return 'Password must be at least 6 characters';
                                }
                                return null;
                              },
                            ),
                            const SizedBox(height: 24),
                            _isLoading
                                ? const SizedBox(
                                    height: 50,
                                    child: Center(child: CircularProgressIndicator()),
                                  )
                                : SizedBox(
                                    width: double.infinity,
                                    height: 50,
                                    child: ElevatedButton(
                                      onPressed: _login,
                                      style: ElevatedButton.styleFrom(
                                        backgroundColor: const Color(0xFF2563EB),
                                        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                                        padding: const EdgeInsets.symmetric(vertical: 12),
                                      ),
                                      child: const Text(
                                        'Login',
                                        style: TextStyle(
                                          fontSize: 16,
                                          fontWeight: FontWeight.w600,
                                          color: Colors.white,
                                        ),
                                      ),
                                    ),
                                  ),
                            const SizedBox(height: 16),
                            // System notification permission button
                            if (NotificationService.isSystemNotificationSupported && !NotificationService.isSystemNotificationEnabled)
                              TextButton.icon(
                                onPressed: () async {
                                  final granted = await NotificationService.requestPermission();
                                  if (granted) {
                                    ScaffoldMessenger.of(context).showSnackBar(
                                      const SnackBar(content: Text('Notifications enabled!')),
                                    );
                                    setState(() {}); // Refresh to hide button
                                  } else {
                                    ScaffoldMessenger.of(context).showSnackBar(
                                      const SnackBar(content: Text('Notification permission denied.')),
                                    );
                                  }
                                },
                                icon: const Icon(Icons.notifications_active, size: 18),
                                label: const Text('Enable System Notifications'),
                                style: TextButton.styleFrom(
                                  foregroundColor: Colors.grey.shade700,
                                  padding: const EdgeInsets.symmetric(vertical: 8),
                                ),
                              ),
                          ],
                        ),
                      ),
                    ),
                    const SizedBox(height: 24),
                  ],
                ),
              ),
            ),
          ),
          Positioned(
            top: MediaQuery.of(context).padding.top + 10,
            right: 20,
            child: TextButton.icon(
              onPressed: _showAboutDialog,
              icon: const Icon(Icons.help_outline, color: Colors.white),
              label: const Text(
                'About',
                style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold),
              ),
              style: TextButton.styleFrom(
                backgroundColor: Colors.white.withOpacity(0.2),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
                padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
